spring.application.name=assetflow-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/assetflow
spring.datasource.username=assetflow
spring.datasource.password=assetflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true