spring.datasource.url=jdbc:postgresql://localhost:5432/assetflow
spring.datasource.username=assetflow
spring.datasource.password=assetflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.com.assetflow.backend=INFO

app.cors.allowed-origin=http://localhost:4200

app.jwt.secret=mysecretkeymysecretkeymysecretkeymysecretkey

app.business-zone=Europe/Stockholm
